### PR TITLE
Update package metadata

### PR DESCRIPTION
**Pull request by ofek**
## Background

Hello there! The Python packaging ecosystem has standardized on the interface for build backends ([PEP 517](https://peps.python.org/pep-0517/)/[PEP 660](https://peps.python.org/pep-0660/)) and the format for metadata declaration ([PEP 621](https://peps.python.org/pep-0621/)/[PEP 631](https://peps.python.org/pep-0631/)). As a result, the execution of `setup.py` files is now [deprecated](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html).

So, I'm spending my free time updating important projects so that they are modernized and set an example for others 😄

## Summary of changes

This implements [PEP 621](https://peps.python.org/pep-0621/), obviating the need for `setup.py` and `MANIFEST.in`. The build backend `hatchling` (of which I am a maintainer in the [PyPA](https://github.com/pypa)) is now used as that is the default in the official [Python packaging tutorial](https://packaging.python.org/en/latest/tutorials/packaging-projects/). Hatchling is available on all the major distribution channels such as [Debian](https://salsa.debian.org/python-team/packages/hatchling), [Fedora](https://src.fedoraproject.org/rpms/python-hatchling), [Arch Linux](https://archlinux.org/packages/community/any/python-hatchling/), [conda-forge](https://anaconda.org/conda-forge/hatchling), [Nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/hatchling/default.nix), [Alpine Linux](https://github.com/alpinelinux/aports/blob/master/community/py3-hatchling/APKBUILD), [FreeBSD](https://github.com/freebsd/freebsd-ports/blob/main/devel/py-hatchling/Makefile)/[OpenBSD](https://github.com/openbsd/ports/blob/master/devel/py-hatchling/Makefile), [Gentoo Linux](https://github.com/gentoo/gentoo/tree/master/dev-python/hatchling), [MacPorts](https://github.com/macports/macports-ports/blob/master/python/py-hatchling/Portfile), [OpenEmbedded](https://github.com/openembedded/openembedded-core/commit/846e806181f1349be29cbce78c5041735dfd7e6f), [Spack](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-hatchling/package.py), etc.

The earliest supported Python 3 version of Hatchling is 3.7, therefore I've also set that as the minimum here. Python 3.6 is EOL and other build backends like `flit-core` and `setuptools` also dropped support. Python 3.6 only accounted for ~8% of downloads in the last month: https://pypistats.org/packages/pycountry

## Notes

- This resolves https://github.com/flyingcircusio/pycountry/issues/118
- We should probably remove the Python upper bound constraint as upper bounds for libraries are heavily discouraged by the community, see https://iscinumpy.dev/post/bound-version-constraints/
- In future versioning could be simplified by using [hatch-vcs](https://github.com/ofek/hatch-vcs)

### CODE REVIEW

**Comment by ctheune** [comment]
Sounds good. Unfortunately this repo still has the black/pre-commit bug... le sigh. :)

**Review by ctheune — APPROVED** [review]

**Comment by ctheune** [comment]
I fixed the main branch wrt/pre-commit. Would you mind rebasing?

**Comment by ofek** [comment]
Rebased!

**Comment by ofek** [comment]
Would you mind triggering the CI with that button below?

**Comment by ofek** [comment]
@ctheune bumping in case you missed ^ 🙂

**Comment by ofek** [comment]
Just let me know if I can help!

**Comment by ctheune** [comment]
Sorry for not picking this up earlier. I'm getting pycountry ready to accept more contributors in the future. I did decide to switch to poetry, though. So sorry for dismantling your current work ... but if you wouldn't mind reviewing the way I updated it now, then I would welcome that a lot! ❤️

**Comment by ofek** [comment]
Got it, thanks!

**Pull request closed without merging**
