### PR TITLE
Migrate to 4.11.0 Release of Debian's pkg-isocodes

### PR DESCRIPTION
**Pull request by nschimmoller**

### CODE REVIEW

**Comment by nschimmoller** [comment]
image

image

**Comment by nschimmoller** [comment]
@ctheune I believe based upon your comment in closing Pull #81 these ones should be eligible to be added given the current version of the ISO 3166-2 file in debian. https://salsa.debian.org/iso-codes-team/iso-codes/-/blob/main/data/iso_3166-2.json

**Comment by nschimmoller** [comment]
If it'd be better to align this file to the file on debian as opposed to just adding single subdivisions at a time. Happy to make another commit to the PR prior to merge.

**Comment by nschimmoller** [comment]
@ctheune figured out how to execute the Makefile and updated the generate.py file to indicate it is now using debian 4.10.0's release of ISO codes based upon comment on Issue #94. This also now addresses Issue #126

**Comment by nschimmoller** [comment]
Consolidating comments in this PR from prior for simplicity of documentation. @ctheune I think this is a pretty high quality PR at this point hope to get it approved for merge 🤞

### Impact of Changes:
------------------------
- Addresses Issue #117 
- Resolves Issue #94 and #126 
    - Brings functionality in line with documentation
    - Bring PyCountry to latest release of Debian's pkg-iso codes as of commit
- Adds documentation for Issue #114 to the ReadMe
- Moves release to 

### [Debian Changelog](https://salsa.debian.org/iso-codes-team/iso-codes/-/blob/main/CHANGELOG.md):
------------------------
#### 4.10.0 - 2022-06-01

##### Added

- Update ISO 639-2 codes to include Montenegrin (cnr) added in 2017.
- Update ISO 4217 to add Venezuelan Bolivar Soberano
- ISO 639-3: New translation for Friulian
- ISO 639-5: New translations for Esperanto, Hindi, Russian
- ISO 4217: New translation for Esperanto

##### Changed

- Translation updates for ISO 3166-1
- Translation updates for ISO 3166-2
- Translation updates for ISO 3166-3
- Translation updates for ISO 639-2
- Translation updates for ISO 639-3
- Translation updates for ISO 639-5
- Translation updates for ISO 4217
- Translation updates for ISO 15924

##### Fixed

- ISO 3166-2: Add parent codes for GB and country and provincial subdivisions (Wales, Northern Ireland, Wales, and England).
- ISO 3166-2: Fix subdivision names for Finland to contain both Finnish and Swedish names.

#### 4.11.0 – 2022-07-25

##### Added

- Update ISO 639-3 codes from SIL website. Adds tok ISO 639-3 code for the Toki Pona language.

##### Changed

- Translation updates for ISO 3166-1
- Translation updates for ISO 3166-2
- Translation updates for ISO 3166-3
- Translation updates for ISO 639-2
- Translation updates for ISO 639-3
- Translation updates for ISO 639-5
- Translation updates for ISO 4217
- Translation updates for ISO 15924

**Comment by nschimmoller** [comment]
@llimeht question. When you ran the `Makefile` back in November how did you ensure that the process did not replace the now defunct iso3166.mo files?

**Comment by llimeht** [comment]
@nschimmoller, I don't recall running `make` at all; I ran `generate.py` by hand and I didn't make an sdist. As best as I can see from my shell history, I did:

```
$ git add generate.py
$ git commit -m"Enable importer to find iso-codes v4.8.0"
$ python3 generate.py
$ shopt globstar
$ git add src/pycountry/**/*.mo 
$ git add src/pycountry/databases/iso3166-*
$ git add -i -p
$ git commit -m"Import data for iso-codes v4.8.0"
$ git commit -m"Update test for data change: number of subdivisions"
[and more work on tests]
```
(interactive editing obviously not shown in that)

**Comment by nschimmoller** [comment]
@llimeht thanks so much for the timely response! I think at this point this PR is pretty tight but still just need to hear back from @ctheune for merging unless you happen to know another maintainer of the project

**Pull request merged**
