### PR TITLE
Use iso-codes 4.12.0 from Debian

### LINKED ISSUE #148: UN registers 'Türkiye' as new country name to replace 'Turkey'
In 2022-06 [the UN accepted a request by the Turkish Foreign Minister to change the name of the country from "Turkey" to "Türkiye"](https://www.aa.com.tr/en/americas/un-registers-turkiye-as-new-country-name-to-replace-turkey/2603492). This has been updated in the [UN M.49](https://unstats.un.org/unsd/methodology/m49/) as well as the [Debian iso-codes package as of version 4.12.0](https://salsa.debian.org/iso-codes-team/iso-codes/-/blob/main/CHANGELOG.md#4120-2022-11-06).

Can you update it here too? Thank you!

### PR DESCRIPTION
**Pull request by alanorth**
Update `generate.py` to use iso-codes 4.12.0 from Debian and re-generate all assets.

Fixes #148.

### CODE REVIEW

**Comment by atocharnaud** [comment]
Hi, any chance to get a new version with this commit included? Merci. Arnaud Atoch

**Comment by hofrob** [comment]
@osnyx @ctheune Can you take a look at this PR?

**Comment by jkdaza** [comment]
@ctheune would it be OK to merge this, please?
The issue of the name of the Republic of Türkiye is becoming a pressing one.
Thanks

**Comment by alanorth** [comment]
On this note, [iso-codes 4.13.0 was just released yesterday](https://salsa.debian.org/iso-codes-team/iso-codes/-/blob/main/CHANGELOG.md#4130-2023-02-28). There are a few changes to common names there (makes me wonder if the tests in this project are woking?).

**Comment by zware** [comment]
This is superseded by #156, but v4.15.0 is now available.  This one should probably be closed.

**Pull request closed without merging**
